### ISSUE TITLE
Feedback on week 9 project progress for CS2113T-F11-2

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-F11-2/main#142]
## Team progress for `v1.2`
* [x] Team PR created to the upstream repository with the title `[AY1920S1-CS2113T-F11-2] Contact List Pro`(:exclamation:)
* Milestone `v1.2` properly managed:
   * [x] A suitable deadline 2019-10-17 set(:heavy_check_mark: well done!)
   * [x] Issues allocated to it https://github.com/AY1920S1-CS2113T-F11-2/main/issues/136 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/135 https://github.com/AY1920S1-CS2113T-F11-2/main/pull/124 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/101 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/99 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/98 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/91 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/90 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/20 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/15 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/13 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/9 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/8 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/7 (:heavy_check_mark: well done!)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [x] Milestone explicitly closed(:heavy_check_mark: well done!)
   * [x] Code tagged as `v1.2`(:heavy_check_mark: well done!)
* Milestones setup:
   * [x] Milestone `v1.2` setup(:heavy_check_mark: well done!)
   * [x] Milestone `v1.3` setup(:heavy_check_mark: well done!)
   * [x] Milestone `v1.4` setup(:heavy_check_mark: well done!)
* Milestone v1.3 planned:
   * [x] A suitable deadline 2019-10-31 set(:heavy_check_mark: well done!)
   * [x] Issues allocated to it https://github.com/AY1920S1-CS2113T-F11-2/main/issues/134 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/100 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/96 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/95 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/94 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/93 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/92 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/88 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/87 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/86 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/85 (:heavy_check_mark: well done!)
## Individual progress of @omupenguin for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-F11-2/main/issues/136 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/135 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/90 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/8 (:heavy_check_mark: well done!)
## Individual progress of @weng-kexin for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-F11-2/main/issues/9 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/8 (:heavy_check_mark: well done!)
## Individual progress of @yetong1895 for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-F11-2/main/issues/101 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/91 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/7 (:heavy_check_mark: well done!)
## Individual progress of @tatayu for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-F11-2/main/issues/99 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/98 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/7 (:heavy_check_mark: well done!)

Tutor: @andyrobert3

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-10-18 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
