### ISSUE TITLE
Feedback on week 12 project progress for CS2113T-F11-2

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-F11-2/main#259]
## Team progress for mid-`v1.4`
* Milestones setup:
   * [x] Milestone `v1.4` setup(:heavy_check_mark: well done!)
* Milestone `v1.4` properly managed:
   * [x] A suitable deadline set [your deadline: 2019-11-14] (:exclamation: try to do by next milestone)
   * [x] Issues allocated to it e.g., https://github.com/AY1920S1-CS2113T-F11-2/main/issues/255 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/247 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/245 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/244 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/243 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/242 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/241 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/240 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/239 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/238 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/237 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/236 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/235 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/234 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/233 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/232 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/231 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/230 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/229 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/228 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/227 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/226 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/225 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/224 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/223 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/222 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/221 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/220 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/219 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/218 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/217 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/216 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/215 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/214 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/213 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/212 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/211 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/209 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/208 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/207 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/206 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/205 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/204 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/203 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/202 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/201 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/200 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/199 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/188 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/153 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/145 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/100 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/97 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/94 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/87 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/86 (:heavy_check_mark: well done!)
## Individual progress of @omupenguin for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F11-2/main/issues/247 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/209 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/205 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/203 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/188 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/153 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/145 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @weng-kexin for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F11-2/main/issues/247 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/243 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/226 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/153 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @yetong1895 for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F11-2/main/issues/247 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/153 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/94 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @tatayu for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F11-2/main/issues/247 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/153 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/97 https://github.com/AY1920S1-CS2113T-F11-2/main/issues/86 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @andyrobert3

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-08 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
